### ISSUE TITLE
Dependency issue occurring during make vm process?

### ISSUE THREAD

**Issue by malachig** [genome/gms#16]
Getting the following error when I try to run make vm from a fresh checkout now:

The following packages have unmet dependencies:

genome-snapshot-deps : Depends: genome-snapshot-deps-r 

(=2013.09.06-1~Ubuntu~precise) but it is not going to be installed

E: Unable to correct problems, you have held broken packages.

make: **\* [done-host/pkgs] Error 100
make: **\* [vm] Error 2

**Comment by mcallaway** [comment]
I've been working on this all day. I think it's fixed now.

On Oct 3, 2013, at 4:34 PM, Malachi Griffith notifications@github.com
wrote:

Getting the following error when I try to run make vm from a fresh checkout
now:

The following packages have unmet dependencies:

genome-snapshot-deps : Depends: genome-snapshot-deps-r

(=2013.09.06-1~Ubuntu~precise) but it is not going to be installed

E: Unable to correct problems, you have held broken packages.

make: **\* [done-host/pkgs] Error 100
make: **\* [vm] Error 2

—
Reply to this email directly or view it on
GitHubhttps://github.com/genome/gms/issues/16
.

**Comment by malachig** [comment]
Sweet.  Attempting a run from a fresh clone right now...

**Comment by malachig** [comment]
Hmmm,

I still get the same error from a fresh install running 'make vm' from the host, or 'make' from within the vm.

**Comment by sakoht** [comment]
It currently dump and tar up a mirror of out repo.  Perhaps I should do it from all repos to truly control what packages will be used.  For CLIA at least.

**Comment by mcallaway** [comment]
I'll need to run it to see the error, but It's likely the problems I faced
yesterday with genome deps related to R. The biocunductor repo went away
and the r-Debian  repo was not a full mirror so I had to populate our
internal repo with packages from our apt cache.

More later as I get into this.

On Oct 4, 2013, at 12:28 AM, Scott Smith notifications@github.com wrote:

It currently dump and tar up a mirror of out repo. Perhaps I should do it
from all repos to truly control what packages will be used. For CLIA at
least.

Sent from my iPhone

> On Oct 3, 2013, at 8:40 PM, Malachi Griffith notifications@github.com
> wrote:
> 
> Hmmm,
> 
> I still get the same error from a fresh install running 'make vm' from
> the host, or 'make' from within the vm.
> 
> —
> Reply to this email directly or view it on GitHub.

—
Reply to this email directly or view it on
GitHubhttps://github.com/genome/gms/issues/16#issuecomment-25677225
.

**Comment by sakoht** [comment]
Is the bioconductor repo gone just temporarily?

Seems like a big part of R...

**Comment by mcallaway** [comment]
Scott, can you regenerate the package of genome dependencies?  We need the updated genome-snapshot-deps (and R within it).  Also, can you send me the instructions for how to maintain/update those tarballs?

**Comment by sakoht** [comment]
I'm not totally sure what you mean by "regenerate the package of genome dependencies".  Do you mean to just do the normal stuff with the genome-snapshot-deps checkout?  I can do it, though Nathan Nutter invented this version, and is the real expert on it.

For those tarballs: I just updated the README in setup/stage/.  That directory also has a Makefile to rebuild the apt mirror tgz.

**Comment by mcallaway** [comment]
Am I wrong that you build a local alt repo from a tarball representing our
internal repo?  The genomesnapshot deps that is available is old and
broken.

On Oct 8, 2013, at 9:36 PM, Scott Smith notifications@github.com wrote:

I'm not totally sure what you mean by "regenerate the package of genome
dependencies". Do you mean to just do the normal stuff with the
genome-snapshot-deps checkout? I can do it, though Nathan Nutter invented
this version, and is the real expert on it.

For those tarballs: I just updated the README in setup/stage/. That
directory also has a Makefile to rebuild the apt mirror tgz.

—
Reply to this email directly or view it on
GitHubhttps://github.com/genome/gms/issues/16#issuecomment-25943018
.

**Comment by sakoht** [comment]
Sent from my iPhone

> On Oct 8, 2013, at 7:51 PM, Matt Callaway notifications@github.com wrote:
> 
> Am I wrong that you build a local alt repo from a tarball representing our 
> internal repo?

Yep:

cd setup/stage
cat README
make

> The genomesnapshot deps that is available is old and 
> broken. 

I'm behind in this.  But in back at TGI tomorrow.

Do we have it fixed internally at TGI?

If not, can we reverse engineer the package list from a machine that has everything installed from last time it worked?

**Comment by sakoht** [comment]
I am driving but you want to talk give me a ring.

**Comment by mcallaway** [comment]
I'm headed to bed. The genome deps is fixed internally. I'll make a new
tarball tomorrow. Don't text and drive! :)

On Oct 8, 2013, at 10:03 PM, Scott Smith notifications@github.com wrote:

I am driving but you want to talk give me a ring.

Sent from my iPhone

> On Oct 8, 2013, at 7:51 PM, Matt Callaway notifications@github.com
> wrote:
> 
> Am I wrong that you build a local alt repo from a tarball representing
> our
> internal repo? The genomesnapshot deps that is available is old and
> broken.
> 
> On Oct 8, 2013, at 9:36 PM, Scott Smith notifications@github.com wrote:
> 
> I'm not totally sure what you mean by "regenerate the package of genome
> dependencies". Do you mean to just do the normal stuff with the
> genome-snapshot-deps checkout? I can do it, though Nathan Nutter invented
> this version, and is the real expert on it.
> 
> For those tarballs: I just updated the README in setup/stage/. That
> directory also has a Makefile to rebuild the apt mirror tgz.
> 
> —
> Reply to this email directly or view it on
> GitHubhttps://github.com/genome/gms/issues/16#issuecomment-25943018
> .
> —
> Reply to this email directly or view it on GitHub.

—
Reply to this email directly or view it on
GitHubhttps://github.com/genome/gms/issues/16#issuecomment-25943770
.

**Comment by sakoht** [comment]
Dude, voice text.

**Comment by sakoht** [comment]
On one hand, I hate using a dumped repo at all.

On the other, we should probably dump a mirror of all of the repos we depend on.

Perhaps ideally we do both, dump them, and let people choose to use the dumped repo or not.  The dump is better for consistency.

Stopped now at a veggie French restaurant in Berkeley. :)  (Only in Berkeley.)

**Comment by mcallaway** [comment]
I think the dumped repo is a terrible idea. :)

We should be using real repos for everything, and making sure they work
right.  We should follow up with our dev team to figure out why internal to
public sync doesn't happen automatically.

**Comment by sakoht** [comment]
Sent from my iPhone

> On Oct 9, 2013, at 9:28 AM, Matt Callaway notifications@github.com wrote:
> 
> I think the dumped repo is a terrible idea. :) 

It's certainly a somewhat ugly solution to cope with other unsolved problems.

I don't know how much time people have for more optimal solutions.  If you are game for tackling it that would be great.

The thing that would be helpful for the paper and release would be the puppet stuff, particularly if we can get the solr search working, and the related crons.  That stuff is really slick and we have it disabled in the release.

> We should be using real repos for everything, and making sure they work 
> right. We should follow up with our dev team to figure out why internal to 
> public sync doesn't happen automatically. 

Jenkins used-to do it I think.

**Comment by sakoht** [comment]
I updated setup/stage/Makefile and pushed it.  Also ran the make to create a new apt mirror, and am staging it now.

Now "make" should re-create the apt repo, with a timestamp for the date in question, and also stage the data so it will eventually end up on the FTP/HTTP site.

It does not automatically stage to S3 because the tool I was using to do that doesn't run on Lucid.

**Comment by malachig** [comment]
This issue appears to be resolved.  We have been successfully running through multiple fresh installation attempts on various systems, both straight ubuntu 12.04 and ubuntu within a VM on a MacPro Desktop and MacPro laptop.

Right now the install is running smoothly and as far as well can tell, all tools needed to prime the database, launch builds, use lsf (openlava), etc. are successfully installed in the standalone GMS.
